format and fix shellcheck diagnostics

diff --git a/.local/bin/optgif b/.local/bin/optgif
--- a/.local/bin/optgif
+++ b/.local/bin/optgif
@@ -2,16 +2,16 @@
 
 filename=$1
 
-if [ ! -f $filename ]; then
-  echo "File not found"
-  exit 1
+if [ ! -f "$filename" ]; then
+	echo "File not found"
+	exit 1
 fi
 
-size=$(identify -format "%wx%h\n" $1 | head -1)
-filewithoutext=$(basename $1 .gif)
+size=$(identify -format "%wx%h\n" "$1" | head -1)
+filewithoutext=$(basename "$1" .gif)
 
-ffmpeg -y -i $1 -vf palettegen palette.png
-ffmpeg -y -i $1 -i palette.png \
-  -filter_complex paletteuse -r 10 -s $size "$(echo "$filewithoutext")_comp.gif"
+ffmpeg -y -i "$1" -vf palettegen palette.png
+ffmpeg -y -i "$1" -i palette.png \
+	-filter_complex paletteuse -r 10 -s "$size" "$filewithoutext"_comp.gif
 
 rm palette.png
